name: run.yml
on:
  #schedule:
  #  - cron: '*/1 * * * *'
  workflow_dispatch:


jobs:
  generateImages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Run Script
        run: |
          chmod +x ./getLinks.sh
          ./getLinks.sh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
